### ISSUE TITLE
error running notebooks

### ISSUE THREAD

**Issue by ajankowski** [awjuliani/oreilly-rl-tutorial#4]
Trying to run first 2 notebooks (bandits) I get below error:
"TypeError: object of type 'numpy.int64' has no len()"

**Comment by ghost** [comment]
Same error. To fix : 
line 205 unityenv.py, add np.int64 :  if isinstance(action, (int, np.int_, np.int64)):

**Comment by awjuliani** [comment]
Just made the change!
